language: node_js
node_js:
  - "12.2.0"

before_install:
  - npm i npm@6.9.0 -g

jobs:
  include:
    - stage: lint
      script: npm run lint:stylelint
      script: npm run lint:eslint
    - stage: test
      script: npm run test
